name: Build
on:
  push:
    # タグ付きpushの時にする
    tags:

    # TODO: 後で消す
    branches:
      - migrate/github-actions

  # 手動ビルドもできるように(いる？)
  workflow_dispatch:

jobs:
  build:
    name: build-images
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare image tags
        run: |
          echo "FORMATTED_BRANCH_NAME=$(echo ${{ github.ref_name }} | sed -e 's/\//-/g' )" >> $GITHUB_ENV
      - name: "Build and Push"
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/misskeyio/misskey:latest
            ghcr.io/misskeyio/misskey:${{ env.FORMATTED_BRANCH_NAME }}
